### ISSUE TITLE
NES Games Seem Incorrect

### ISSUE THREAD

**Issue by kwhat** [jdratlif/ggencoder-qt#1]
I am having a hard time getting what I consider the correct value with this utility for NES codes.

Game Genie Code: PEUZUGAA

Expected Value: 01
Expected Address: ACB3
Expected Compare: 00

The values I got with the [JS conversion](http://games.technoplaza.net/ggencoder/js/) were more correct, but still not there:

JS Value: 01
JS Address: 2CB3
JS Compare: 00

QT Versions appears to be more broken than the JS version:

QT Value: 01
QT Address: 2CB3
QT Compare: 04

**Comment by jdratlif** [comment]
I'll go look into this and see what I can find.

**Comment by jdratlif** [comment]
Okay, here is what I've figured out based on my notes and the code.

NES game genie codes use 7 bits, not 8, for the address. So the code you supplied is for the address 0x2CB3. Because NES ROM code is mapped starting at 0x8000, you need to add 0x8000 to get the CPU address. The eighth bit, which looks like it turns the value into ACB3, is actually encoding the fact that this is an 8 character rather than a 6 character code.

As to why not show 0xACB3 instead of 0x2CB3...well, that gets complicated. Technically, that's not what the game genie code has. A CPU address is not what the game genie code is using. The game genie knows to fix that. That might make it difficult if you wanted to put raw codes into an emulator, but at that point, there's a lot more information that might be needed that is beyond the scope of my project. It might be worth a note or tooltip or something though.

As for the difference in the Qt/C++ and the JavaScript version, I don't see that difference. I get the same result on both. I'm using Windows 10 (Firefox for the JS version). I used the Win32 build from 2008. Are you using a different binary? Did you build it from source? Are you on a Mac? I made some changes to the source to make it comply with C++11. It's possible I introduced a bug.

The JavaScript code is almost identical to the C++ code. I pretty much copied it verbatim. There is a bug in the JavaScript version where it treats 0 and no-compare as the same thing and generates the wrong code, but that's a different thing that needs fixed.
